### PR TITLE
Update vtkRosPointCloudSubscriber.cpp

### PR DESCRIPTION
**Pull request by diogomartinsac**
Fix data type.

### CODE REVIEW

**Comment by mauricefallon** [comment]
@benoit-robotics : can you test this please?

**Comment by benoit-robotics** [comment]
ConvertPointCloud2ToVtk expects an argument of type pcl::PCLPointCloud2Ptr so it cannot be correct.
@diogomartinsac What are you trying to achieve ? What is your build error ? Maybe you are using another version of pcl_plugin ?

**Comment by diogomartinsac** [comment]
Maybe I'm using another version of pcl_plugin. I tried to follow the repository instructions but had a compiling error regarding the data type. After the change, it worked. I'm using ROS Noetic and Ubuntu 20.04.

**Comment by benoit-robotics** [comment]
I am closing this PR, tell us if you have other issues

**Pull request closed without merging**
